name: poc_zig_htmx_pgdb
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: northstar
      POSTGRES_PASSWORD: northstar
      POSTGRES_DB: northstar
    ports:
      - "5457:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U northstar -d northstar"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - northstar_pg_data:/var/lib/postgresql/data

volumes:
  northstar_pg_data:
